const products=[
{id:1,name:'CALI MOUSSE MONSTER',cat:'Nouveautés',tags:'papaya tropical summer',badge:'ÉDITION',desc:'Présentation visuelle de la collection. Consultation informative.',img:'assets/images/product.jpeg'},
{id:2,name:'DRY LEMON',cat:'Collections',tags:'lemon agrumes',badge:'COLLECTION',desc:'Identité citronnée et présentation premium.',img:'assets/images/product.jpeg'},
{id:3,name:'FILTRE X3 90u',cat:'Exclusivités',tags:'90u filtre',badge:'EXCLUSIF',desc:'Référence de collection présentée à titre informatif.',img:'assets/images/product.jpeg'},
{id:4,name:'PURPLE KUSH',cat:'Collections',tags:'purple violet',badge:'COLLECTION',desc:'Univers violet de la sélection LAZERMY.',img:'assets/images/product.jpeg'}];
const tracks=[1,2,3,4].map(n=>({title:`LAZERMY ${String(n).padStart(2,'0')}`,artist:'LAZERMY RADIO',src:`music/track0${n}.mp3`}));
let fav=JSON.parse(localStorage.getItem('lzFav')||'[]'),page='home',filter='Tous',q='',track=+(localStorage.getItem('lzTrack')||0);const app=document.querySelector('#app'),audio=document.querySelector('#audio');
function saveFav(){localStorage.setItem('lzFav',JSON.stringify(fav))}function card(p){return `<article class="card"><img src="${p.img}" alt=""><div class="body"><button class="heart" onclick="toggleFav(${p.id})">${fav.includes(p.id)?'♥':'♡'}</button><div class="meta">${p.cat} · ${p.badge}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="actions"><span class="status">● Disponible à la consultation</span><button class="view" onclick="detail(${p.id})">Voir</button></div></div></article>`}
function visible(){return products.filter(p=>(filter==='Tous'||p.cat===filter)&&(p.name+' '+p.cat+' '+p.tags).toLowerCase().includes(q.toLowerCase()))}function tabs(){return `<div class="tabs">${['Tous','Nouveautés','Collections','Exclusivités'].map(x=>`<button class="${filter===x?'active':''}" onclick="setFilter('${x}')">${x.toUpperCase()}</button>`).join('')}</div>`}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));let html='';if(['home','catalog','collections','favorites'].includes(page)){let list=visible();if(page==='favorites')list=list.filter(p=>fav.includes(p.id));if(page==='collections')list=list.filter(p=>p.cat==='Collections'||p.cat==='Exclusivités');html=`${page==='home'?'<section class="hero"><div class="meta">LAZERMY V4</div><h1>La sélection.</h1><p>Une identité sombre, précise et sans détour.</p></section>':''}${tabs()}<section class="grid">${list.map(card).join('')||'<div class="panel">Aucun résultat</div>'}</section>`}else if(page==='radio')html=radioPage();else if(page==='contact')html=`<div class="panel"><h2>Contact</h2><p>Message · FAQ · Support</p><form onsubmit="sendMsg(event)"><input required placeholder="Nom"><input required placeholder="Sujet"><textarea required rows="5" placeholder="Message"></textarea><button class="primary">ENVOYER</button></form><p id="sent"></p></div>`;else if(page==='profile')html=`<div class="panel"><h2>Profil</h2><p>Profil local LAZERMY</p><input id="profileName" value="${localStorage.getItem('lzName')||''}" placeholder="Nom"><input id="profileUser" value="${localStorage.getItem('lzUser')||''}" placeholder="Pseudo"><button class="primary" onclick="saveProfile()">Modifier le profil</button><p>${fav.length} favori(s)</p></div>`;else if(page==='team')html=`<div class="panel"><h2>Équipe</h2><p>Espace d’administration local. Les secrets et jetons privés ne doivent jamais être stockés dans cette application publique.</p></div>`;else if(page==='info')html=`<div class="panel"><h2>Informations</h2><p>À propos · Conditions · Confidentialité · Contact</p><p>LAZERMY V4 — catalogue informatif.</p></div>`;else if(page==='settings')html=settings();app.innerHTML=html}
function go(p){page=p;closeDrawer();render()}function setFilter(f){filter=f;render()}function toggleFav(id){fav=fav.includes(id)?fav.filter(x=>x!==id):[...fav,id];saveFav();render()}function detail(id){let p=products.find(x=>x.id===id);app.innerHTML=`<div class="panel detail"><button onclick="render()">← Retour</button><img src="${p.img}"><div class="meta">${p.cat}</div><h2>${p.name}</h2><p>${p.desc}</p><button class="primary" onclick="toggleFav(${p.id})">${fav.includes(p.id)?'Retirer des favoris':'Ajouter aux favoris'}</button></div>`}
function radioPage(){return `<div class="panel"><h2>LAZERMY RADIO</h2><p>4 emplacements audio personnalisables.</p>${tracks.map((t,i)=>`<button class="playlistRow" onclick="loadTrack(${i},true)"><span>${t.title}</span><span>${i===track?'●':'▶'}</span></button>`).join('')}<div class="switch"><span>Volume</span><input type="range" min="0" max="1" step=".05" value="${audio.volume}" oninput="audio.volume=this.value"></div></div>`}
function settings(){let anim=localStorage.getItem('lzAnim')!=='0';return `<div class="panel"><h2>Paramètres</h2><div class="switch"><span>Animations</span><button onclick="localStorage.setItem('lzAnim','${anim?'0':'1'}');render()">${anim?'Activées':'Désactivées'}</button></div><button class="primary" onclick="fav=[];saveFav();render()">Effacer les favoris</button><button class="primary" onclick="localStorage.clear();location.reload()">Réinitialiser les préférences</button></div>`}
function sendMsg(e){e.preventDefault();document.querySelector('#sent').textContent='Message enregistré sur cet appareil.';e.target.reset()}function saveProfile(){localStorage.setItem('lzName',profileName.value);localStorage.setItem('lzUser',profileUser.value);render()}
function loadTrack(i,play=false){track=(i+tracks.length)%tracks.length;localStorage.setItem('lzTrack',track);audio.src=tracks[track].src;trackTitle.textContent=tracks[track].title;trackArtist.textContent=tracks[track].artist;if(play)audio.play().catch(()=>{});if(page==='radio')render()}function togglePlay(){if(!audio.src)loadTrack(track);audio.paused?audio.play().catch(()=>{}):audio.pause()}audio.addEventListener('play',()=>play.textContent='⏸');audio.addEventListener('pause',()=>play.textContent='▶');audio.addEventListener('ended',()=>loadTrack(track+1,true));
function closeDrawer(){drawer.classList.remove('open');shade.classList.remove('on')}menu.onclick=()=>{drawer.classList.add('open');shade.classList.add('on')};shade.onclick=closeDrawer;searchBtn.onclick=()=>searchBox.classList.toggle('open');search.oninput=e=>{q=e.target.value;render()};prev.onclick=()=>loadTrack(track-1,true);next.onclick=()=>loadTrack(track+1,true);play.onclick=togglePlay;playlist.onclick=()=>go('radio');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));loadTrack(track);render();
