const products=[['Filtrée 90U','90 micron'],['Monster Calimousse – Papaya','Summer Edition'],['Super Lemon Dry','Lemon Collection'],['Purple Kush','Purple Collection']];let fav=JSON.parse(localStorage.getItem('lzfav')||'[]');const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function go(id){$$('.page').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo(0,0);if(id==='favorites')renderFav();$('#favCount').textContent=fav.length}$$('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));
function card(p,i){return `<article class="card" data-i="${i}"><div class="art">${String(i+1).padStart(2,'0')}</div><button class="fav" data-f="${i}">${fav.includes(i)?'♥':'♡'}</button><div class="body"><h3>${p[0]}</h3><p>${p[1]}</p><button class="more">DÉCOUVRIR →</button></div></article>`}
function wire(){$$('.fav').forEach(b=>b.onclick=e=>{e.stopPropagation();let i=+b.dataset.f;fav=fav.includes(i)?fav.filter(x=>x!==i):[...fav,i];localStorage.setItem('lzfav',JSON.stringify(fav));renderAll()});$$('.more').forEach(b=>b.onclick=()=>detail(+b.closest('.card').dataset.i))}
function render(){let q=$('#search')?.value?.toLowerCase()||'';$('#cards').innerHTML=products.map((p,i)=>[p,i]).filter(x=>x[0][0].toLowerCase().includes(q)).map(x=>card(x[0],x[1])).join('');wire()}function renderHome(){$('#homeCards').innerHTML=products.map((p,i)=>card(p,i)).join('');wire()}function renderFav(){$('#favCards').innerHTML=fav.map(i=>card(products[i],i)).join('');$('#emptyFav').style.display=fav.length?'none':'block';wire()}function renderAll(){render();renderHome();renderFav();$('#favCount').textContent=fav.length}
function detail(i){let p=products[i];$('#detail').innerHTML=`<div class="detailHero">${String(i+1).padStart(2,'0')}</div><h1>${p[0]}</h1><p class="lead">${p[1]}</p><div class="panel"><b>PRIVATE SELECTION</b><p>Découvre cette référence et ajoute-la à tes favoris.</p></div>`;$('#modal').classList.add('open')}$('#close').onclick=()=>$('#modal').classList.remove('open');$('#searchBtn').onclick=()=>{go('catalog');$('#search').focus()};$('#search').oninput=render;$('#resetFav').onclick=()=>{fav=[];localStorage.removeItem('lzfav');renderAll()};
$('#contactForm').onsubmit=e=>{e.preventDefault();let n=$('#name').value.trim(),m=$('#message').value.trim();$('#msgResult').innerHTML=`<b>Message prêt.</b><br>${n} : “${m.replace(/</g,'&lt;')}”`};
const tracks=['track1.mp3','track2.mp3','track3.mp3','track4.mp3'];let ti=0,a=$('#audio');function load(){a.src='music/'+tracks[ti];$('#track').textContent='LAZERMY RADIO — '+(ti+1);$('#state').textContent=tracks[ti]}function playing(){return !a.paused}function start(){a.play().then(()=>{$('#play').textContent='Ⅱ';$('#disc').classList.add('spin')}).catch(()=>$('#state').textContent='Ajoute '+tracks[ti]+' dans /music')}
$('#play').onclick=()=>{if(!a.src)load();if(a.paused)start();else{a.pause();$('#play').textContent='▶';$('#disc').classList.remove('spin')}};$('#next').onclick=()=>{ti=(ti+1)%4;load();start()};$('#prev').onclick=()=>{ti=(ti+3)%4;load();start()};$('#disc').onclick=()=>$('#play').click();a.onended=()=>$('#next').click();$('#playlist').onclick=()=>$('#trackList').classList.toggle('open');$('#trackList').innerHTML=tracks.map((t,i)=>`<button data-track="${i}">${i+1}. ${t}</button>`).join('');$$('[data-track]').forEach(b=>b.onclick=()=>{ti=+b.dataset.track;load();start();$('#trackList').classList.remove('open')});renderAll();if(window.Telegram?.WebApp){Telegram.WebApp.ready();Telegram.WebApp.expand()}
