const products=[
{group:'Sélection 01',id:1,name:'CALI MOUSSE MONSTER',cat:'Nouveautés',tags:'papaya tropical summer',badge:'ÉDITION',desc:'Présentation visuelle de la collection. Consultation informative.',img:'cali-mousse-monster.jpg.jpeg'},
{group:'Sélection 02',id:2,name:'DRY LEMON',cat:'Collections',tags:'lemon agrumes',badge:'COLLECTION',desc:'Identité citronnée et présentation premium.',img:'dry-lemon.jpg.jpeg'},
{group:'Sélection 03',id:3,name:'FILTRE X3 90u',cat:'Exclusivités',tags:'90u filtre',badge:'EXCLUSIF',desc:'Référence de collection présentée à titre informatif.',img:'filtre-x3-90u.jpg.jpeg'},
{group:'Sélection 04',id:4,name:'PURPLE KUSH',cat:'Collections',tags:'purple violet',badge:'COLLECTION',desc:'Univers violet de la sélection LAZERMY.',img:'purple-kush.jpg.jpeg'},
{group:'Sélection 01',id:5,name:'STRAWBERRY TRADITIONNEL',cat:'Collections',tags:'strawberry tropical traditionnel resine texture fondante aromes naturels selection soignee premium coffeeshop',badge:'COLLECTION',desc:'Fiche informative du visuel : résine traditionnelle, texture fondante, arômes naturels, sélection soignée et univers tropical. Le visuel mentionne également « qualité coffeeshop » et « Tropical Vibes ».',img:'strawberry-traditionnel.png'},
{group:'Sélection 03',id:6,name:'GRAPE CREAM',cat:'Exclusivités',tags:'grape cream raisin elementra labs wpff usa premium texture fondante selection exclusive',badge:'EXCLUSIF',desc:'Fiche informative du visuel : Elementra Labs, WPFF USA, arômes raisin, texture fondante, qualité premium et sélection exclusive. Le conditionnement illustré porte la mention 50G.',img:'grape-cream.png'},
{group:'Sélection 02',id:7,name:'LEMON THAI',cat:'Nouveautés',tags:'lemon thai vice city citron agrumes plasma static premium texture fondante selection exclusive',badge:'NOUVEAU',desc:'Fiche informative du visuel : Lemon Thai / Vice City Hash, mention Plasma Static, arômes citronnés, texture fondante, qualité premium et sélection exclusive.',img:'lemon-thai.jpeg'},
{group:'Sélection 03',id:8,name:'AREA 51',cat:'Exclusivités',tags:'area 51 static sift 139 73 premium aromes puissants texture fondante selection exclusive galactic vibes',badge:'EXCLUSIF',desc:'Fiche informative du visuel : Area 51, mention Static Sift 139/73, arômes puissants, texture fondante, qualité premium, sélection exclusive et univers « Galactic Vibes ».',img:'area-51.jpeg'},
{group:'Sélection 04',id:9,name:'MOCHI COCO',cat:'Collections',tags:'mochi coco meltmaniac by doc frozensift premium 139 120 thc rich aromes intenses texture fondante selection exclusive',badge:'COLLECTION',desc:'Fiche informative du visuel : Mochi Coco / Meltmaniac by Doc, mention Frozensift Premium 139/120, arômes intenses, texture fondante et sélection exclusive. Le visuel comporte également la mention « THC Rich ».',img:'mochi-coco.jpeg'},
{group:'Sélection 04',id:10,name:'TROPICANA COOKIES',cat:'Galerie',tags:'tropicana cookies secret grower tropical cookie notes tropicales aromes texture',badge:'VISUEL',desc:'Fiche informative basée sur le visuel : Tropicana Cookies / Secret Grower. L’affiche mentionne notamment goût cookie, notes tropicales, arômes intenses et texture résineuse.',img:'tropicana-cookies.jpeg'},
{group:'Sélection 04',id:11,name:'TROPICANA CHERRY',cat:'Galerie',tags:'tropicana cherry secret grower cherry cerise aromes texture',badge:'VISUEL',desc:'Fiche informative basée sur le visuel : Tropicana Cherry / Secret Grower. L’affiche met en avant un univers cerise et mentionne des arômes intenses ainsi qu’une texture résineuse.',img:'tropicana-cherry.jpeg'},
{group:'Sélection 03',id:12,name:'FORBIDDEN FRUIT × FRUIT JOY',cat:'Galerie',tags:'forbidden fruit fruit joy secret grower fruits murs glace notes fruitees',badge:'VISUEL',desc:'Fiche informative basée sur le visuel : Forbidden Fruit × Fruit Joy / Secret Grower. L’affiche mentionne fruits mûrs, touche glacée, vapeur dense et notes fruitées.',img:'forbidden-fruit-fruit-joy.jpeg'}];
const tracks=[1,2,3,4].map(n=>({title:`LAZERMI ${String(n).padStart(2,'0')}`,artist:'LAZERMI RADIO',src:`track0${n}.mp3.mp3`}));
let fav=JSON.parse(localStorage.getItem('lzFav')||'[]'),page='home',filter='Tous',q='',track=+(localStorage.getItem('lzTrack')||0);const app=document.querySelector('#app'),audio=document.querySelector('#audio');
function saveFav(){localStorage.setItem('lzFav',JSON.stringify(fav))}
const gameStats=[['G 1','🎾 10'],['G 2','🎾 20'],['G 3','🎾 30'],['G 4','🎾 40'],['G 5','🎾 50']];
function gameStatsHTML(){return `<div class="gameStats">${gameStats.map(([g,c])=>`<div class="gameStatRow"><span>${g}</span><span class="gameArrow">→</span><strong>${c}</strong></div>`).join('')}</div>`}
function card(p){return `<article class="card"><div class="cardMedia"><img src="${p.img}" alt="">${gameStatsHTML()}</div><div class="body"><button class="heart" onclick="toggleFav(${p.id})">${fav.includes(p.id)?'♥':'♡'}</button><div class="meta">${p.cat} · ${p.badge}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="actions"><span class="status">● Disponible à la consultation</span><button class="view" onclick="detail(${p.id})">Voir</button></div></div></article>`}
function visible(){return products.filter(p=>(page!=='catalog'||filter==='Tous'||p.group===filter)&&(p.name+' '+p.cat+' '+p.tags).toLowerCase().includes(q.toLowerCase()))}function tabs(){return `<div class="tabs">${['Tous','Sélection 01','Sélection 02','Sélection 03','Sélection 04'].map(x=>`<button class="${filter===x?'active':''}" onclick="setFilter('${x}')">${x.toUpperCase()}</button>`).join('')}</div>`}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));let html='';if(['home','catalog','favorites'].includes(page)){let list=visible();if(page==='favorites')list=list.filter(p=>fav.includes(p.id));html=`${page==='home'?'<section class="hero"><div class="meta">LAZERMI OFFICIEL</div><h1>Bienvenue chez LAZERMI OFFICIEL.</h1><p>Découvrez notre univers, une sélection soignée et une présentation pensée dans les moindres détails.</p></section>':''}${page==='catalog'?tabs():''}<section class="grid">${list.map(card).join('')||'<div class="panel">Aucun résultat</div>'}</section>`}else if(page==='radio')html=radioPage();else if(page==='contact')html=`<div class="panel"><h2>Contact</h2><p>La Maille · Message · FAQ · Support</p><form onsubmit="sendMsg(event)"><input required placeholder="Nom"><input required placeholder="Sujet"><textarea required rows="5" placeholder="Message"></textarea><button class="primary">ENVOYER</button></form><p id="sent"></p></div>`;else if(page==='profile')html=`<div class="panel"><h2>Profil</h2><p>Profil local LAZERMI OFFICIEL</p><input id="profileName" value="${localStorage.getItem('lzName')||''}" placeholder="Nom"><input id="profileUser" value="${localStorage.getItem('lzUser')||''}" placeholder="Pseudo"><button class="primary" onclick="saveProfile()">Modifier le profil</button><p>${fav.length} favori(s)</p></div>`;else if(page==='team')html=`<div class="panel"><h2>Équipe</h2><p><strong>Une équipe en forme, des idées en mouvement et une exigence constante.</strong></p><p>LAZERMI OFFICIEL met l’accent sur une présentation soignée, une identité forte et des produits sélectionnés avec attention pour leur qualité.</p></div>`;else if(page==='info')html=`<div class="panel"><h2>Informations</h2><p>À propos · Conditions · Confidentialité · Contact</p><p>LAZERMI OFFICIEL — catalogue informatif.</p></div>`;else if(page==='settings')html=settings();app.innerHTML=html}
function go(p){page=p;closeDrawer();render()}function setFilter(f){filter=f;render()}function toggleFav(id){fav=fav.includes(id)?fav.filter(x=>x!==id):[...fav,id];saveFav();render()}function detail(id){let p=products.find(x=>x.id===id);app.innerHTML=`<div class="panel detail"><button onclick="render()">← Retour</button><img src="${p.img}"><div class="meta">${p.cat}</div><h2>${p.name}</h2><p>${p.desc}</p><button class="primary" onclick="toggleFav(${p.id})">${fav.includes(p.id)?'Retirer des favoris':'Ajouter aux favoris'}</button></div>`}
function fmt(t){if(!Number.isFinite(t))return '0:00';let m=Math.floor(t/60),s=Math.floor(t%60);return `${m}:${String(s).padStart(2,'0')}`}
function radioPage(){return `<div class="panel radioPanel"><h2>LAZERMI RADIO</h2><p>4 emplacements audio personnalisables.</p><div class="vinylWrap"><div class="vinyl ${audio.paused?'':'spinning'}"><div class="vinylLabel">LZ</div></div><div class="vinylInfo"><b>${tracks[track].title}</b><small>${tracks[track].artist}</small></div></div>${tracks.map((t,i)=>`<button class="playlistRow" onclick="loadTrack(${i},true)"><span>${t.title}</span><span>${i===track?'●':'▶'}</span></button>`).join('')}<div class="seekBlock"><div class="timeLine"><span id="radioCurrent">${fmt(audio.currentTime)}</span><span id="radioDuration">${fmt(audio.duration)}</span></div><input id="seek" class="seekRange" type="range" min="0" max="1000" value="${audio.duration?Math.round(audio.currentTime/audio.duration*1000):0}" oninput="seekAudio(this.value)"></div><div class="switch"><span>Volume</span><input type="range" min="0" max="1" step=".05" value="${audio.volume}" oninput="setVolume(this.value)"></div></div>`}
function seekAudio(v){if(Number.isFinite(audio.duration)&&audio.duration>0){audio.currentTime=(+v/1000)*audio.duration;rememberAudio()}}
function setVolume(v){audio.volume=+v;localStorage.setItem('lzVolume',audio.volume)}
function rememberAudio(){localStorage.setItem('lzTrack',track);localStorage.setItem('lzTime',String(audio.currentTime||0))}
function updateRadioProgress(){if(page!=='radio')return;let seek=document.querySelector('#seek'),cur=document.querySelector('#radioCurrent'),dur=document.querySelector('#radioDuration');if(seek&&audio.duration)seek.value=Math.round(audio.currentTime/audio.duration*1000);if(cur)cur.textContent=fmt(audio.currentTime);if(dur)dur.textContent=fmt(audio.duration)}
function settings(){let anim=localStorage.getItem('lzAnim')!=='0';return `<div class="panel"><h2>Paramètres</h2><div class="switch"><span>Animations</span><button onclick="localStorage.setItem('lzAnim','${anim?'0':'1'}');render()">${anim?'Activées':'Désactivées'}</button></div><button class="primary" onclick="fav=[];saveFav();render()">Effacer les favoris</button><button class="primary" onclick="localStorage.clear();location.reload()">Réinitialiser les préférences</button></div>`}
function sendMsg(e){e.preventDefault();document.querySelector('#sent').textContent='Message enregistré sur cet appareil.';e.target.reset()}function saveProfile(){localStorage.setItem('lzName',profileName.value);localStorage.setItem('lzUser',profileUser.value);render()}
function loadTrack(i,play=false,restore=false){track=(i+tracks.length)%tracks.length;localStorage.setItem('lzTrack',track);audio.src=tracks[track].src;audio.load();trackTitle.textContent=tracks[track].title;trackArtist.textContent=tracks[track].artist;audio.onloadedmetadata=()=>{if(restore){let saved=+(localStorage.getItem('lzTime')||0);if(saved>0&&saved<audio.duration)audio.currentTime=saved}updateRadioProgress()};if(play)audio.play().catch(()=>{});if(page==='radio')render()}function togglePlay(){if(!audio.getAttribute('src'))loadTrack(track,false,true);audio.paused?audio.play().catch(()=>{}):audio.pause()}audio.addEventListener('play',()=>{play.textContent='⏸';if(page==='radio')render()});audio.addEventListener('pause',()=>{play.textContent='▶';rememberAudio();if(page==='radio')render()});audio.addEventListener('timeupdate',()=>{updateRadioProgress();if(Math.floor(audio.currentTime)%5===0)rememberAudio()});audio.addEventListener('ended',()=>{localStorage.setItem('lzTime','0');loadTrack(track+1,true)});
function closeDrawer(){drawer.classList.remove('open');shade.classList.remove('on')}menu.onclick=()=>{drawer.classList.add('open');shade.classList.add('on')};shade.onclick=closeDrawer;searchBtn.onclick=()=>searchBox.classList.toggle('open');search.oninput=e=>{q=e.target.value;render()};prev.onclick=()=>loadTrack(track-1,true);next.onclick=()=>loadTrack(track+1,true);play.onclick=togglePlay;playlist.onclick=()=>go('radio');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));audio.volume=+(localStorage.getItem('lzVolume')||0.8);loadTrack(track,false,true);render();
